name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  # CI job for testing and linting across multiple Node.js versions
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["12", "14", "16", "20"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run Lint
        run: npm run lint
      - name: Run Test
        run: npm run test
      - name: Run Build
        run: npm run build

  # Build and deploy job (runs once with a single Node.js version)
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install dependencies and build
        run: npm ci && npm run build
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACTAPP_F85C5 }}
          channelId: live
          projectId: reactapp-f85c5

  notify:
    needs: [ci, cd]
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification - Success
        if: success() # Notify on success
        uses: slackapi/slack-github-action@v1.21.0
        with:
          payload: |
            {
              "text": "🎉 **Production Deployment Successful!** 🎉\nYour app has been successfully deployed to Firebase Hosting using Node.js version: ${{ env.NODE_VERSION }}."
            }
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Slack Notification - Failure
        if: failure() # Notify on failure
        uses: slackapi/slack-github-action@v1.21.0
        with:
          payload: |
            {
              "text": "🚨 **Production Deployment Failed!** 🚨\nSomething went wrong with the deployment to Firebase Hosting. Please check the logs for details."
            }
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
