# name: Check CI Jobs
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: setup node
#         uses: actions/setup-node@v2
#         with:
#           node-version: 20
#       - name: Install dependencies
#         run: npm install
#       - name: Run Line
#         run: npm run lint
#         # continue-on-error: false
#       - name: Run Test
#         run: npm run test
#         # continue-on-error: false
#       - name: Run Build
#         run: npm run build
